# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              CircleOver
description:        Documentation and tutorials about circleover.com

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://circleover.com"

# Site logo, image or text
brand:
    image:          logo.png  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Docs      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Mohamed El-masry
    github:     circleover    # Github username for avatar

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    peter:
        name:       Mohamed El-masry
        github:     circleover    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://facebook.com/circleover
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://instagram.com/circleover
    linkedin:
    pinterest:
    twitter:        https://twitter.com/circleover
    vimeo:          
    youtube:        
    reddit:         

# Twitter share button
twitter_username: circleover

# Default footer image settings
footer:
    copyright:      Made by a human somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true
